### ISSUE TITLE
error running yo suit component-name 

### ISSUE THREAD

**Issue by cmnstmntmn** [suitcss/generator-suit#9]
the wizards works as expected until last step, when it fails to generate the component.

```
events.js:154
      throw er; // Unhandled 'error' event
      ^
AssertionError: Trying to copy from a source that does not exist: /Users/constantin/Sites/mysite/resources/suit-my-component/gitignore
    at EditionInterface.exports._copySingle (/usr/local/lib/node_modules/generator-suit/node_modules/mem-fs-editor/lib/actions/copy.js:45:3)
    at EditionInterface.exports.copy (/usr/local/lib/node_modules/generator-suit/node_modules/mem-fs-editor/lib/actions/copy.js:23:17)
    at EditionInterface.module.exports [as move] (/usr/local/lib/node_modules/generator-suit/node_modules/mem-fs-editor/lib/actions/move.js:4:8)
    at module.exports.yeoman.generators.Base.extend.writing (/usr/local/lib/node_modules/generator-suit/generators/app/index.js:94:13)
    at /usr/local/lib/node_modules/generator-suit/node_modules/yeoman-generator/lib/base.js:430:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
constantin@Constantins-MacBook-Pro suit-my-component (master) $ 
```

npm: 3.8.0
node: v5.5.0

**Comment by simonsmith** [comment]
Hey, were you creating a component or util, or both?

**Comment by cmnstmntmn** [comment]
this is my project tree 

![tree](https://cloud.githubusercontent.com/assets/2312755/14465802/fb69d4ec-00dc-11e6-90b5-688d8bd8adcf.png)

**Comment by simonsmith** [comment]
Ah yes, I can see this error when using the generator as well. Thanks for the report

**Comment by giuseppeg** [comment]
@cmnstmntmn did you try to uninstall the old version first? Assuming that you are upgrading.

**Comment by simonsmith** [comment]
I'm seeing it with a fresh install of `1.0.0`

**Comment by cmnstmntmn** [comment]
@giuseppeg was a fresh install also

**Comment by giuseppeg** [comment]
I googled a bit and the following issues seem to be related:
https://github.com/npm/npm/issues/7252
https://github.com/yeoman/generator-polymer/issues/240

**Comment by simonsmith** [comment]
I don't see a general fix in those issue, I'm not trying to do an `npm publish`. Are you saying it works fine for you @giuseppeg?

**Comment by giuseppeg** [comment]
I updated node and npm and it doesn't work for me either.
I did publish the package and that's when the files got deleted I guess.

```bash
$ ls -al ~/.npm-packages/lib/node_modules/generator-suit/generators/app/templates/
total 40
drwxr-xr-x  8 giuseppe  staff   272 Apr 13 09:46 .
drwxr-xr-x  4 giuseppe  staff   136 Apr 13 09:46 ..
-rw-r--r--  1 giuseppe  staff    64 Mar 25 10:20 CHANGELOG.md
-rw-r--r--  1 giuseppe  staff  1038 Mar 25 10:20 LICENSE.md
-rw-r--r--  1 giuseppe  staff  1187 Mar 25 10:20 README.md
-rw-r--r--  1 giuseppe  staff    40 Mar 25 10:20 index.css
drwxr-xr-x  4 giuseppe  staff   136 Apr 13 09:46 lib
-rw-r--r--  1 giuseppe  staff  1025 Mar 25 10:20 package.json
```

**Comment by giuseppeg** [comment]
Deleting the `files` field from the `package.json` template fixed the issue.
@simonsmith  Alternatively we can keep the `files` field and rename `package.json` to `packagejson`

**Comment by giuseppeg** [comment]
Deleting the `files` field from the `package.json` template fixed the issue.
@simonsmith Alternatively we can keep the `files` field and rename `package.json` to `packagejson`.

**Comment by giuseppeg** [comment]
I went for the second solution

**Comment by cmnstmntmn** [comment]
hmm, is not working; there are also other files *travis.yml*, *editor*

**Comment by giuseppeg** [comment]
@cmnstmntmn try to:
- clone the repo
- apply the changes from https://github.com/suitcss/generator-suit/pull/10/files

and from the generator folder

```bash
npm pack && tar xzvf generator-suit-1.0.0.tgz
```
or

```bash
npm uninstall generator-suit
npm link
cd ../ && mkdir -p test-component && cd $_
yo suit test-component
```

this time it should work.

**Comment by simonsmith** [comment]
1.0.1 working fine for me. Nice one @giuseppeg

**Comment by giuseppeg** [comment]
Nice. Yesterday I was thinking that the source of this issue could be `npm3`.
Because the tests never failed before.
